### ISSUE TITLE
Update documentation about reference genomes

### ISSUE THREAD

**Issue by marchoeppner** [nf-core/deepvariant#12]
Hi,

I can tell from the config files that there is probably some central "repository" from which to get the reference genomes and the various auxiliary files. But the documentation is missing any clues as to how to get those files. There is section 4 of the instructions (Reference genomes), but that doesn't point to anything right now. 

Cheers,
Marc

**Comment by ewels** [comment]
The [documentation about reference genomes](https://github.com/nf-core/deepvariant/blob/master/docs/usage.md#reference-genomes) is out of date and needs revising (it's not a lifebit s3 bucket, it's the main deepvariant bucket).

**Comment by ewels** [comment]
New documentation merged to dev. I hope everything is now clearer @marchoeppner!
