### ISSUE TITLE
shub://nf-core/deepvariant missing?

### ISSUE THREAD

**Issue by patrickbryant1** [nf-core/deepvariant#13]
Hi, I am following your tutorial: https://github.com/nf-core/deepvariant/blob/master/docs/installation.md
and am trying to do: singularity pull --name nf-core-deepvariant.simg shub://nf-core/deepvariant
- I get the following error message:
WARNING: Authentication token file not found : Only pulls of public images will succeed
FATAL:   Failed to get manifest from Shub: The requested manifest was not found in singularity hub

I have also looked in shub and the file seems to be missing.
Any suggestions?

**Comment by apeltzer** [comment]
Yeah, we don't really use Singularity Hub at all, thats why this fails:

Use 

```
singularity pull --name nf-core-deepvariant.simg docker://nfcore/deepvariant:latest
```

**Comment by patrickbryant1** [comment]
Thank you!

**Comment by PhilPalmer** [comment]
Hope that's clearer now. I've corrected the documentation on the dev branch to have the correct command
