### ISSUE TITLE
Wrong results location in pipeline complete 

### ISSUE THREAD

**Issue by tarak77** [nf-core/deepvariant#15]
Hi,
I was trying out the test pipeline mentioned in this repo, it runs fine 

```
=========================================
[warm up] executor > local
[b0/f25f59] Submitted process > get_software_versions
[8f/b18f3b] Submitted process > preprocess_bam (NA12878_S1.chr20.10_10p1mb.bam)
[af/6f2fe2] Submitted process > make_examples (NA12878_S1.chr20.10_10p1mb.bam)
[d5/ad6e27] Submitted process > call_variants (NA12878_S1.chr20.10_10p1mb.bam)
[7b/1cec4c] Submitted process > postprocess_variants (NA12878_S1.chr20.10_10p1mb.bam)
[nf-core/deepvariant] Pipeline Complete! You can find your results in /Users/tarakshisode/.nextflow/assets/nf-core/deepvariant/results
```
But for some reason I cannot find the results in that path. Any help?

**Comment by apeltzer** [comment]
This is a bug: 

https://github.com/nf-core/deepvariant/blob/2b5486356c4dbd4dcb598b611281997119c2e350/main.nf#L516

Should be pointing simply to 

```
${params.outdir}
```

@PhilPalmer Can fix this I suppose :-) 

For you, just use the second part of this suggestion:

`./results`

**Comment by tarak77** [comment]
I see, thanks

**Comment by PhilPalmer** [comment]
Thanks, it's now changed on the dev branch
