### ISSUE TITLE
trouble running the program

### ISSUE THREAD

**Issue by felipemartins1305** [nf-core/deepvariant#17]
hello all

I am experimeting with running this next flow and I've been having difficulties. I ran a basic folder with 5 bam files today and received an usual error message that I have attached here.
The data was downloaded, but I checked it on IGV and all the files have the same areas sequenced. I generated bai file using samtools and bed files using bedtools. Can someone help me figure out what;s wrong? wWe would like to implement Deepvariant on our pipeline for large amounts of data.

Thanks a lot, Felipe

[error.log](https://github.com/nf-core/deepvariant/files/2774203/error.log)

**Comment by PhilPalmer** [comment]
Hi @felipemartins1305,

Sorry for the late response and thanks for trying out the pipeline. Are you still having problems running it?

I think the error is caused from specifying multiple bed files in your command:
```bash
./nextflow run main.nf --exome --hg19 --bam_folder /home/user/Downloads/DeepVariant/Z --bed /home/user/Downloads/DeepVariant/Z/Z01.sorted.bed /home/user/Downloads/DeepVariant/Z/Z02.sorted.bed /home/user/Downloads/DeepVariant/Z/Z04.sorted.bed /home/user/Downloads/DeepVariant/Z/Z06.sorted.bed /home/user/Downloads/DeepVariant/Z/Z07.sorted.bed
```

I can see in the log file you sent that it's trying to run the first BED file `Z01.sorted.bed` with the worng BAM file `Z07.sorted.bam` which then causes the error about the contigs not being common among the input files

Unfortaunely the pipeline does not currently support input from multiple BED files.

So I think you will have to run the pipeline for each of your BAM files in your `bam_folder` individually eg:
```
./nextflow run main.nf --exome --hg19 --bam /home/user/Downloads/DeepVariant/Z/Z07.sorted.bam --bed /home/user/Downloads/DeepVariant/Z/Z07.sorted.bed
```
And then do the same for the other four BAM/BED files

Hope that helps, let me know if not or if you run into any more problems.
Thanks

**Comment by felipemartins1305** [comment]
Thanks a lot!
