### ISSUE TITLE
disk space

### ISSUE THREAD

**Issue by felipemartins1305** [nf-core/deepvariant#18]
Hello

I have been able to run the program successfully. The problem is that I realized that the /Deepvariant/work folder is now over 200Gb in size!! is there a way to delete some of these files safely and open more disk space?

**Comment by PhilPalmer** [comment]
Hi @felipemartins1305,

So the `work` directory is produced by Nextflow and contains all of the intermediary files. 
If you have all of the files you need in your `results` directory then it should be safe to delete the whole folder.

One of the main reasons why the work directory can be useful is to resume failed jobs from the last successful process by adding the `-resume` flag (as long as the earlier processses/inputs have not changed). However if your jobs have completed successfully then it sounds like there is little need for this, (assuming you have all of the files you need in your results directory).

You can delete the whole directory with the following command, **be sure you want to delete it though as this cannot be undone**
```
rm -rf work
```

Not sure if I have answered your question exactly, let me know if not
