### ISSUE TITLE
no outfiles

### ISSUE THREAD

**Issue by felipemartins1305** [nf-core/deepvariant#20]
Hello

Sorry for being here again.
After I thought all issues were done, I moved the folder containing DeepVariant to a different HD with more space. I ran the program and got thumbs up (log attached) except... there were no outfiles. Nothing was saved. I don't know why. It's all the same except that things moved in the machine.
Here's the command line:

sudo ./nextflow run main.nf --exome --h38 --bam_folder /media/user/segundoHD/FA/1/FA_1_N33.bam --bed /media/user/segundoHD/FA/FA_BEDs/FA_1_N33.bed

Thanks a lot, Felipe

[log_what.txt](https://github.com/nf-core/deepvariant/files/2895256/log_what.txt)

**Comment by PhilPalmer** [comment]
Hi @felipemartins1305,

No worries, sorry the pipeline isn't working for you as expected.

I think the problem here is that the `bam_folder` should be set to the folder containing the BAM files (in this case `/media/user/segundoHD/FA/1`) and not the BAM file itself.

If you want to run the pipeline for your `FA_1_N33.bam` BAM file try using the `--bam` option instead eg:
```bash
sudo ./nextflow run main.nf --exome --h38 --bam /media/user/segundoHD/FA/1/FA_1_N33.bam --bed /media/user/segundoHD/FA/FA_BEDs/FA_1_N33.bed
```

Sorry that the pipeline was not failing for you and giving any useful error messages in this sitatuation though. I will check that the documentation is clear and see if there's a way to make the pipeline fail in this situation.

**Comment by felipemartins1305** [comment]
Dear Phil:

Thanks for the quick reply.
Your suggestion will not solve the problem. The command --bam doesn't go. Every time I try to use it it gives me an error message (see below). In this case it is a different issue. I will try to ask someone that knows Linux more than me, I'm sure it's something to do with changing folders, I must have made somtething wrong in the process.

Thanks, Felipe

**Comment by felipemartins1305** [comment]
N E X T F L O W  ~  version 18.10.1
Launching `main.nf` [fabulous_montalcini] - revision: 0f2d95c8e6
WARN: Access to undefined parameter `bam_folder` -- Initialise it to a default value eg. `params.bam_folder = some_value`
ERROR ~ please specify --bam_folder option (--bam_folder bamfolder). Expression: (nextflow.ast.LangHelpers.compareEqual(params.bam_folder, true) && nextflow.ast.LangHelpers.compareEqual(params.bam_folder, null))

 -- Check script 'main.nf' at line: 141 or see '.nextflow.log' file for more details

**Comment by PhilPalmer** [comment]
Hi @felipemartins1305,

I think I know the problem. I think you are running the pipeline that this was forked from. I.e. [lifebit-ai/DeepVariant](https://github.com/lifebit-ai/DeepVariant) and not [nf-core/deepvariant](https://github.com/nf-core/deepvariant). There are some differences between the parameters for the two pipelines as you can see below.
You can check which repository you're using by entering inside your deepvariant directory and typing:
```
git remote -v
```

It should return:
```
origin	https://github.com/nf-core/deepvariant.git (fetch)
origin	https://github.com/nf-core/deepvariant.git (push)
```

and not:
```
origin	https://github.com/lifebit-ai/DeepVariant.git (fetch)
origin	https://github.com/lifebit-ai/DeepVariant.git (push)
```

Also something I didn't spot before was that you should use `--genome h38` and not `--h38` and if you're using docker make sure you use `-profile standard,docker`. 
Your command should probably look something like this:
```
sudo ./nextflow run main.nf --exome --genome h38 --bam /media/user/segundoHD/FA/1/FA_1_N33.bam --bed /media/user/segundoHD/FA/FA_BEDs/FA_1_N33.bed -profile standard,docker
```

Do you know which repository you're using and does that help at all?
Also where are you running this pipeline, is this on your own local machine? Is it for a particular project?

**Comment by felipemartins1305** [comment]
Hello

Yes, it is for a particular project and yes, I am running on my local machine. I downloaded the correct one now as you pointed, but it seems I have multiplied the error messages. The most uninformative one is below:

WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.

**Comment by PhilPalmer** [comment]
Can you please upload the `.nextflow.log` file?

I don't know if the error message you sent is causing the issue or if its something else. The error message you sent may just be a warning. It looks like its to do with Docker though so I would check your docker installation. Here is an [answer from stackoverflow](https://stackoverflow.com/questions/48685667/what-does-docker-mean-when-it-says-memory-limited-without-swap) for that warning from docker

Alternatively if you are just trying to run DeepVariant in the easiest way possible you could also checkout [Deploit](https://deploit.lifebit.ai/app) from Lifebit. Full disclosure I work there. But it provides a web interface where you can run pipelines including DeepVariant on the cloud and you get $10 free credit. It would mean you wouldn't have to worry about some of the installation/configuration that seems to be a problem. Just an option though and I'll try and help you to get the pipeline running either way

**Comment by felipemartins1305** [comment]
Hello

I finally got it running. I went back to the correct repository, and it took some work - including editing the config file. I am using for so I can run multiple files and it's fine now. Thanks for your help.

**Comment by ewels** [comment]
Hi @felipemartins1305,

I'd be curious to know what kind of config edits you needed to do to make this work - is there anything general that we can change to help other users of the pipeline?

Thanks,

Phil

**Comment by felipemartins1305** [comment]
Hello

The program crashed and had an error message about memory usage. So we went to the config file and changed the Max memory and Max CPUs - I feel like it shouldn't be an issue, but after we changed it everything ran smoothly. I am running in a local machine - this is a test, only 60 bams for now. So this was the only thing I can remember.
If I could  make a suggestion, it would be great if there was a --bed_folder command for running multiple bed files. In a different thread you told me I would have to do one at a time, which led me to use a loop to run all 60 files in one command.

Thanks a lot, Felipe

**Comment by PhilPalmer** [comment]
Hi @felipemartins1305,

That's great that you were able to run it

Yes I agree, that would be a good addition to run with multiple BED files. The main problem would be ensuring that the correct BAM file was run with the correct BED. Would you rather:
1) Have to specify the same file prefix for your BAM & BED files
I think this is what you are doing already, eg `FA_1_N33.bam` & `FA_1_N33.bed`
2) Supply a seperate CSV file that maps the correct BAM to the correct BED file?
I think this might be more difficult to implement but would have the advantage of being able to run multiple BAM files with the same BED file
Eg `example.csv`:
```
FA_1_N33.bam,FA_1_N33.bed
file2.bam,other.bed
file3.bam,another.bed
file4.bam,other.bed
```

And yes, by default the max cpus & max memory are reasonably high for running DeepVariant, as they're for running it in a cloud/HPC enviroment. You can also set your max cpus & memory in the configuration file as you have done or on the command line in your nextflow run command eg:
```
nextflow run main.nf --max_cpus 2 --max_memory 6.GB
```

Thanks

**Comment by felipemartins1305** [comment]
Hi 

I don't remember seeing the  `--max_cpus` and `--max_memory` options, but now that I know they exist, I will definitely use them.
I believe that what I already did - using `.bam` and `.bed` files with the same title - would be the best call. If you use samtools to create the bed files - like I did - they will come with the exact same name as the bam file, so there it is. The other option is not bad though, I think both would work, but I still prefer the first. Just my opinion.

Cheers

**Comment by ewels** [comment]
Hi both,

I'm a little confused - is the `.bed` file not there to specify a region of the genome that's of interest? That's how I interpret `usage.md`:
> _Path to bedfile, specifying region to be analysed must also be supplied_

So then normally you'd have one `.bed` file for an entire project / run...?

If you're using samtools to generate bed files from bam, then that sounds more like the bed file contains all of the aligned read information. If that's the case then (a) we can do this automatically within the pipeline and (b) the documentation should probably be refined to make this clear :)

Phil

**Comment by PhilPalmer** [comment]
Ah yes sorry you're quite right at @ewels,

The BED file is for the regions of interest and so would normally be the same for all of BAM files.

@felipemartins1305, if you want to run DeepVariant for the whole genome sequence I suggest you find a BED file for the h38 reference genome that you are using. I'm sure this will already be available and if not I think you can produce it from the FASTA file.

Thanks
