### ISSUE TITLE
Pipeline Testing

### ISSUE THREAD

**Issue by apeltzer** [nf-core/deepvariant#5]
Double checked already that exome bam and my BED file have compatible contigs but no success unfortunately:

```
leus/io/sam_reader.cc:537] Unrecognized SAM header type, ignoring: 
  I1022 11:53:51.789329 47582124862080 genomics_reader.py:213] Reading hroc113_0.md.bam with NativeSamReader
  I1022 11:53:51.808645 47582124862080 make_examples.py:991] Common contigs are [u'1', u'2', u'3', u'4', u'5', u'6', u'7', u'8', u'9', u'10', u'11', u'12', u'13', u'14', u'15', u'16', u'17', u'18', u'19', u'20', u'21', u'22', u'X', u'Y']
  I1022 11:53:51.819024 47582124862080 genomics_reader.py:213] Reading exons_padded50bp_ucsc_hg19_grch37.bed with NativeBedReader
  I1022 11:54:03.196350 47582124862080 ranges.py:121] Adding interval chr6:117127483-117128419 to intervaltree
  I1022 11:54:14.932882 47582124862080 ranges.py:121] Adding interval chr14:24034765-24034960 to intervaltree
  Traceback (most recent call last):
    File "/scratch/5306779/Bazel.runfiles_7WvCJa/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1188, in <module>
      tf.app.run()
    File "/opt/conda/envs/nf-core-deepvariant-1.0dev/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
      _sys.exit(main(argv))
    File "/scratch/5306779/Bazel.runfiles_7WvCJa/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1178, in main
      make_examples_runner(options)
    File "/scratch/5306779/Bazel.runfiles_7WvCJa/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1076, in make_examples_runner
      regions = processing_regions_from_options(options)
    File "/scratch/5306779/Bazel.runfiles_7WvCJa/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 995, in processing_regions_from_options
      raise ValueError('The regions to call is empty. Check your --regions and '
  ValueError: The regions to call is empty. Check your --regions and --exclude_regions flags to make sure they are not resulting in set of empty region to process. This also happens if you use "chr20" for a BAM where contig names don't have "chr"s (or vice versa).
  parallel: This job failed:
  /opt/conda/envs/nf-core-deepvariant-1.0dev/bin/python /opt/conda/envs/nf-core-deepvariant-1.0dev/share/deepvariant-0.7.0-0/binaries/DeepVariant/0.7.0/DeepVariant-0.7.0+cl-208818123/make_examples.zip --mode calling --ref human_g1k_v37_decoy.fasta.gz --reads hroc113_0.md.bam --regions exons_padded50bp_ucsc_hg19_grch37.bed --examples hroc113_0.md_shardedExamples/hroc113_0.md.bam.tfrecord@1.gz --task 0
  Warning: unable to close filehandle properly: Remote I/O error during global destruction.
```

**Comment by PhilPalmer** [comment]
Hi @apeltzer,

If the bam file is small, would it be possible for you to send the exome bam and BED file? 

Thanks in advance

**Comment by apeltzer** [comment]
BED would be possible, but not the bam (private data) - Anything I can do to find out what's wrong?

**Comment by PhilPalmer** [comment]
I don't think the problem is with the exome model because this runs successfully:
```bash
nextflow run main.nf --exome -profile test,docker
```

I know you said you've checked the bam and bed files but I think there must be some kind of problem with the data. 

The input bam file for `make_examples` uses the convention without the prefix "chr":
```
Common contigs are [u'1', u'2', u'3', u'4', u'5', u'6', u'7', u'8', u'9', u'10', u'11', u'12', u'13', u'14', u'15', u'16', u'17', u'18', u'19', u'20', u'21', u'22', u'X', u'Y']
```
Does the bed file specify them in the same way? 

Also, what was the full command you used?

**Comment by apeltzer** [comment]
I'll try once more! 

This was the command:
```
nextflow run deepvariant/main.nf -profile binac,singularity --fasta /beegfs/work/iiipe01/Reference_Genomes/Human/GRCH37-Sarek/human_g1k_v37_decoy.fasta --bam hroc113_0.md.bam --bed /beegfs/work/iiipe01/Reference_Genomes/Human/GRCH37-Sarek/exons_padded50bp_ucsc_hg19_grch37.bed --exome

```

**Comment by apeltzer** [comment]
(had to add our own hardware profile `binac` here)

**Comment by apeltzer** [comment]
Recreated the BED file and will report back...

**Comment by apeltzer** [comment]
Probably a corrupt BED issue. Its running now, will report back once the results are there!

**Comment by PhilPalmer** [comment]
Okay thanks and yeah DeepVariant can take a while to run, especially if the BAM file is large

**Comment by PhilPalmer** [comment]
Hey @apeltzer, 
I'm assuming the results came back fine. If so do I then have the go-ahead to release deepvariant?

**Comment by apeltzer** [comment]
They didn't unfortunately ... it crashed on the same input. 
[nextflow.log.txt](https://github.com/nf-core/deepvariant/files/2522243/nextflow.log.txt)

**Comment by PhilPalmer** [comment]
Hi @apeltzer,

According to your log file the cause was: 
```
Process `make_examples (hroc113_0.md.bam)` terminated for an unknown reason -- Likely it has been terminated by the external system
```
Is this running on a HPC local cluster?
How big is the bam file/regions being analysed? 

I know `make_examples` is the most computationally intensive process, is it possible that the resources required exceeded the requested resources/limits and so the job was killed?

**Comment by apeltzer** [comment]
> Hi @apeltzer,
> 
> According to your log file the cause was:
> 
> ```
> Process `make_examples (hroc113_0.md.bam)` terminated for an unknown reason -- Likely it has been terminated by the external system
> ```
> 
> Is this running on a HPC local cluster?
> How big is the bam file/regions being analysed?
> 
> I know `make_examples` is the most computationally intensive process, is it possible that the resources required exceeded the requested resources/limits and so the job was killed?

Hm, could be but the system should have ~28 cores and the input was ~5GB in file size. It has 48hours for running through....

**Comment by PhilPalmer** [comment]
We benchmarked DeepVariant internally at Lifebit before and I think at least 50GB of memory is roughly required for a 5GB BAM file to be sure it runs. 
Do you know how much memory you had access to when running DeepVariant?

**Comment by apeltzer** [comment]
The machine I use has ~256GB of memory, 28 CPU cores. I configured just a hardware profile for the system, without other changes. Do you specify that you need that much memory in the process configuration?

**Comment by PhilPalmer** [comment]
It's not specified in the process configuration. The amount of memory required is typically about 10-15x the size of the BAM file. I'm not sure exactly how to specify this in the configuration process. I know that `task.cpus` is used in `make_examples`. Perhaps, it could be this causing the problem if the value of `task.cpus` is too low

**Comment by apeltzer** [comment]
It should be possible to do it using the new (>0.32.0 NXF version) directives. Never used the feature before, so this might not be entirely correct though:

```
file.size() > 1.GB ? {task.memory = 15 * file.size() } : task.memory
```

**Comment by PhilPalmer** [comment]
@apeltzer Okay thanks.
How much memory do you think the job is allocated by default if you did not specify any? Can you also please send the trace file?

**Comment by apeltzer** [comment]
As I didn't change it, it should be 8.GB according to your `base.config`, so I guess that's the biggest issue here.

**Comment by PhilPalmer** [comment]
@apeltzer Please can you try setting the memory in your config file to 50GB and using the with trace option. That way we can test if this is the (only) problem.

I have added this to `make_examples`:
```
process make_examples{

  bamChannel.subscribe {
    if( it.isFile() ) { it.size() > 1000000000 ? {memory = 15 * it.size() } : memory }
  }

  input:
  output:
  script:
}
```
I added the `.subscribe` to be  able to access the individual bam from the channel, but this probably isn't the correct way of doing it. Also what if there are multiple bam files?

I can add this to the documentation as well. It may be easier to just get users to specify the memory/CPUs etc and give guidelines for setting the memory based upon the size of their BAM file

**Comment by PhilPalmer** [comment]
Sorry @apeltzer, what are your thoughts on this and is there any update?
Thanks

**Comment by apeltzer** [comment]
No laptop and I can just have a look at this tomorrow - our Cluster where I ran this is in maintenance till Friday, so can try this then. 

I’ll also have a look in detail, traveling atm and mobile phone is not enough to carefully look etc ...

**Comment by PhilPalmer** [comment]
Hi @apeltzer sorry to keep bothering you

Does the code above (for setting the memory) look alright? 
If you're not able to test the pipeline until Friday would it be alright if I see if anyone else from nf-core can test the pipeline before then instead?

Thanks

**Comment by apeltzer** [comment]
If there are some other people able to test tha twould be good too - I can't test before Friday as the maintenance goes on for now :-1:

**Comment by PhilPalmer** [comment]
So if someone else from nf-core tests deepvariant and it runs successfully will that be okay to release it? Or do you want to make sure you test it yourself on Friday before it can be released?

**Comment by apeltzer** [comment]
Unfortunately that cluster seems to be down still. Can anyone from @nf-core/core have a go and test this?

**Comment by PhilPalmer** [comment]
> Unfortunately that cluster seems to be down still. Can anyone from @nf-core/core have a go and test this?

If anyone does test it, please specify memory in your config file to roughly 10x the size of your BAM file eg 50GB of memory for 5GB BAM file

Thanks

**Comment by PhilPalmer** [comment]
Hi @apeltzer,

Is there any chance the cluster is back up?

Thanks

**Comment by apeltzer** [comment]
```
ssh binac
xyz@login03.binac.uni-tuebingen.de's password: 
Connection closed by 134.2.24.6 port 22
alex@aragorn ~/I/n/e/w/c/c25f32f423ccce54f80c528a174b86> 
```

Sorry no :-1: Getting annoyed by that one too, but can't push them any further to proceed faster ...

**Comment by PhilPalmer** [comment]
Okay thanks, I'll try asking on the gitter chat if anyone wants to test it again if that's alright

**Comment by apeltzer** [comment]
Cluster is back, testing today :-)

**Comment by apeltzer** [comment]
Running - with 50GB memory for the process, also had to update the cluster modules in a file and will send a PR to make that accessible to everyone.

**Comment by PhilPalmer** [comment]
Okay perfect, thanks

**Comment by apeltzer** [comment]
```
=======================================================
Pipeline Name  : nf-core/deepvariant
Pipeline Version: 1.0dev
Bam file       : hroc113_0.md.bam
Bed file       : /beegfs/work/iiipe01/2018-10-21_DeepVariant_Test/WES_targets_centogene.bed
Fasta Ref      : /beegfs/work/iiipe01/Reference_Genomes/Human/GRCH37-Sarek/human_g1k_v37_decoy.fasta
Max Memory     : 128 GB
Max CPUs       : 28
Max Time       : 2d
Model          : wes
Output dir     : results
Working dir    : /beegfs/work/iiipe01/2018-10-21_DeepVariant_Test/work
Container Engine: singularity
Container      : nfcore/deepvariant:dev
Current home   : /home-link/iiipe01
Current user   : iiipe01
Current path   : /beegfs/work/iiipe01/2018-10-21_DeepVariant_Test
Script dir     : /home-link/iiipe01/.nextflow/assets/nf-core/deepvariant
Config Profile : binac
=========================================
[warm up] executor > pbs
WARN: Singularity cache directory has not been defined -- Remote image will be stored in the path: /beegfs/work/iiipe01/2018-10-21_DeepVariant_Test/work/singularity
Pulling Singularity image docker://nfcore/deepvariant:dev [cache /beegfs/work/iiipe01/2018-10-21_DeepVariant_Test/work/singularity/nfcore-deepvariant-dev.img]
[51/a21d26] Submitted process > preprocess_fastagz (human_g1k_v37_decoy.fasta.gz)
[ce/0e0d34] Submitted process > preprocess_gzi (human_g1k_v37_decoy.fasta.gz.gzi)
[bc/9e30f8] Submitted process > get_software_versions
[fb/cfb018] Submitted process > preprocess_fai (human_g1k_v37_decoy.fasta.fai)
[90/f3eb1a] Submitted process > preprocess_bam (hroc113_0.md.bam)
[7f/c309b8] Submitted process > preprocess_gzfai (human_g1k_v37_decoy.fasta.gz.fai)
```

**Comment by apeltzer** [comment]
Unfortunately this hangs and there are no jobs submitted anymore...

**Comment by apeltzer** [comment]
```
[90/f3eb1a] Submitted process > preprocess_bam (hroc113_0.md.bam)

```

That's the bad boy ;-) Pipeline hangs, the other ones ran through properly. Also this is not in the scheduler anymore!

**Comment by PhilPalmer** [comment]
Okay nice, so did deepvariant manage to run successfully or is it still running?

**Comment by apeltzer** [comment]
I will run again right now :-)

**Comment by PhilPalmer** [comment]
Perfect, thanks 😃

**Comment by apeltzer** [comment]
I guess we'd have to find something for the `file.size()` feature, as this causes an error as well:

```
java.lang.AssertionError: Memory unit cannot be a negative number. Expression: (value >= 0). Values: value = -3789259617654013952
        at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:417)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:672)
        at nextflow.util.MemoryUnit.<init>(MemoryUnit.groovy:54)
        at nextflow.util.MemoryUnit.multiply(MemoryUnit.groovy:118)
        at groovy.runtime.metaclass.NumberDelegatingMetaClass.invokeMethod(NumberDelegatingMetaClass.java:75)
        at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at Script8691A4FE657AC67848F69F4B9337B93D$_run_closure1$_closure7$_closure11.doCall(Script8691A4FE657AC67848F69F4B9337B93D:26)
        at Script8691A4FE657AC67848F69F4B9337B93D$_run_closure1$_closure7$_closure11.doCall(Script8691A4FE657AC67848F69F4B9337B93D)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
:

```

**Comment by PhilPalmer** [comment]
@apeltzer is this a problem with the `file.size()` feature itself? As even ignoring the fact that its negative the value is wrong. Do you think the best solution is to change the code back to how it was before and add something in the documentation about setting `memory` to 10x BAM file size?

**Comment by apeltzer** [comment]
No, I don't think that's good - the feature is there and should work :-) 

I'll have a look

**Comment by apeltzer** [comment]
Hm, I'm a bit wondering what we multiple here:

If the `.size()` method returns 0, then that won't help. That size is in bytes, so we'd probably have to run `.toGiga()` to get Gigabytes.

https://www.nextflow.io/docs/latest/script.html?highlight=size#check-file-attributes

```
  memory = { check_max( bam.size().toGiga() * 5.GB  * task.attempt, 'memory')}

```

**Comment by apeltzer** [comment]
I believe it doesn#t resolve the bam channel properly. Having this by default using some reasonable values for memory would be quite user-friendly instead of forcing people to specify it themselves (without having that experience for example).

**Comment by apeltzer** [comment]
Hm, maybe @pditommaso has an idea on how to use this properly. I believe it could also be an issue when we set this in the `base.config` instead of the main script.

**Comment by PhilPalmer** [comment]
@apeltzer I tried adding `toGiga()` eg `memory = { check_max( bam.size().toGiga() * 5.GB  * task.attempt, 'memory')}`

However, when I try running it I get this error:
`Exception in thread "Task submitter" groovy.lang.MissingMethodException: No signature of method: java.lang.Long.toGiga() is applicable for argument types: () values: []`

Do you think this is a problem with the type of `bam.size()` which means I can't call `toGiga()` on it? Do you know how to solve this?

Thanks

**Comment by apeltzer** [comment]
I've asked in the gitter - unfortunately never tried it beforehand and I'm also not sure what causes this ... :-(

**Comment by PhilPalmer** [comment]
Okay no worries, thanks for mentioning it in the gitter chat

**Comment by PhilPalmer** [comment]
Hi @apeltzer, 

Thanks for your help.

I have set the memory as follows:
```nextflow
  memory = { bam.size() < 1000000000 ? 4.GB : check_max( ( bam.size()/1024/1024/1024) * 10.GB * task.attempt, 'memory')}
```

This is mostly the same as you stated in the gitter chat. I added the first part/ternanry operator because I noticed with the small test BAM the memory was being set incredibly low and so it took too long to finish executing the job. So if the BAM is less than 1GB, memory is set to 4GB.

Assuming this is all okay, will we be able to release deepvariant?

**Comment by apeltzer** [comment]
I'm doing another test :-)

**Comment by apeltzer** [comment]
I'm getting this here:

```

Caused by:
  Failed to submit process to grid scheduler for execution

Command executed:

  qsub -N nf-make_example .command.run

Command exit status:
  168

Command output:
  qsub: submit error (Illegal attribute or resource value for Resource_List.mem)

Work dir:
  /beegfs/work/iiipe01/2018-10-21_DeepVariant_Test/work/d7/78ed3a18fda374310837f6ce93b9e7

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
Execution cancelled -- Finishing pending tasks before exit


```

**Comment by PhilPalmer** [comment]
Do you know what the requested resources were?

**Comment by apeltzer** [comment]
`.command.run` says:

```
#PBS -N nf-make_example
#PBS -o /beegfs/work/iiipe01/2018-10-21_DeepVariant_Test/work/d7/78ed3a18fda374310837f6ce93b9e7/.command.log
#PBS -j oe
#PBS -q short
#PBS -l nodes=1:ppn=20
#PBS -l walltime=10:00:00
#PBS -l mem=57.4gb
cd /beegfs/work/iiipe01/2018-10-21_DeepVariant_Test/work/d7/78ed3a18fda374310837f6ce93b9e7

 
```

**Comment by apeltzer** [comment]
(which should be definitely available on that node, having at max 28 cores, 48hours of wall time and 128GB RAM per node...

**Comment by PhilPalmer** [comment]
@apeltzer do you have any idea what the issue may be?

It seems like its an issue with the memory. So the requested memory seems to be within the allowed range but is the format correct? Should it be `57.4GB` instead of `57.4gb` for example?

Does it work if you set the `max_memory` lower?

**Comment by apeltzer** [comment]
Not really, I'm pinging @pditommaso in here ... or you may want to open an issue at the main nextflow repository? Never saw that before using the `file.size()` option

**Comment by ewels** [comment]
Hi guys, just catching up with notifications. Great thread to read! I mentioned this dynamic feature in passing a while back @PhilPalmer - would be really nice to get it working (and may copy syntax for other pipelines if / when this works). Note that the `base.config` should have "sensible defaults", and 8.GB probably isn't. So would be good to minimise how many other config files vary these if possible.

Sounds like we're on track though!

**Comment by PhilPalmer** [comment]
@apeltzer I know I've said this a lot but the pipeline should be ready for testing now 😅 

If you could try running it again that would be much appreciated, thanks

**Comment by PhilPalmer** [comment]
@ewels are you saying the default 8.GB in `base.config` is too high or too low? Shall I change it to 4.GB instead? Are the defaults for the cpus and time okay?
Eg:
```
  cpus = { check_max( 1 * task.attempt, 'cpus' ) }
  memory = { check_max( 4.GB * task.attempt, 'memory' ) }
  time = { check_max( 2.h * task.attempt, 'time' ) }
```
Thanks

**Comment by apeltzer** [comment]
> @apeltzer I know I've said this a lot but the pipeline should be ready for testing now sweat_smile
> 
> If you could try running it again that would be much appreciated, thanks

No worries, yes I can and I will right now :-)

**Comment by apeltzer** [comment]
```
Caused by:
  No signature of method: java.lang.Long.rightShift() is applicable for argument types: (nextflow.util.MemoryUnit) values: [300 GB]
Possible solutions: rightShift(java.lang.Number), leftShift(java.lang.Number)

Source block:
  """
  mkdir logs
  mkdir ${bam.baseName}_shardedExamples
  dv_make_examples.py \
  --cores ${task.cpus} \
  --sample ${bam} \
  --ref ${fastagz} \
  --reads ${bam} \
  --regions ${bed} \
  --logdir logs \
  --examples ${bam.baseName}_shardedExamples
  """

Work dir:
  /beegfs/work/iiipe01/2018-10-21_DeepVariant_Test/work/f8/2723b8b39a0f25ad1d61ba5cea8067

Tip: when you have fixed the problem you can continue the execution appending to the nextflow command line the option `-resume`
Nov-14 13:23:24.273 [Task submitter] INFO  nextflow.Session - Execution cancelled -- Finishing pending tasks before exit
Nov-14 13:23:24.282 [Task submitter] DEBUG nextflow.Session - No signature of method: java.lang.Long.rightShift() is applicable for argu
ment types: (nextflow.util.MemoryUnit) values: [300 GB]
Possible solutions: rightShift(java.lang.Number), leftShift(java.lang.Number)
groovy.lang.MissingMethodException: No signature of method: java.lang.Long.rightShift() is applicable for argument types: (nextflow.util
.MemoryUnit) values: [300 GB]
Possible solutions: rightShift(java.lang.Number), leftShift(java.lang.Number)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:72)
:

```

**Comment by PhilPalmer** [comment]
@apeltzer Okay strange, it seemed to work [here](https://travis-ci.com/nf-core/deepvariant/jobs/158454171), I doubt this would change anything but I updated the version of nextflow to 18.10.1. What version of Nextflow are you using?

I'm not sure if this is causing the error but I'm guessing the memory being set to 300GB is also a problem

**Comment by PhilPalmer** [comment]
Okay I think I understand. The reason why it worked with the Travis build was that the test BAM file is small and so `check_max( bam.size() >> 30 * 10.GB * task.attempt, 'memory')` was never executed (see code below).
```
memory = { bam.size() < 1000000000 ? 4.GB : check_max( bam.size() >> 30 * 10.GB * task.attempt, 'memory')}
```

**Comment by PhilPalmer** [comment]
@apeltzer I think I've fixed it now I think `bam.size() >> 30` just needed to be in wrapped in brackets

**Comment by apeltzer** [comment]
I resubmitted and the job is now queued... I'll update here once I see something going on :-) 

Job is submitted however and seems to not be rejected anymore :+1:

**Comment by PhilPalmer** [comment]
Perfect thanks 🤞

**Comment by apeltzer** [comment]
Looking good :tada: 

```
5369328                    nf-get_software  iiipe01                0 Q short          
5369329                    nf-make_example  iiipe01         02:37:44 C short          
5372698                    nf-call_variant  iiipe01                0 Q short
```

(partially hanging in the queue, but thats not your fault :-))

**Comment by apeltzer** [comment]
Running well, we're postprocessing now :-)

**Comment by PhilPalmer** [comment]
@apeltzer did it manage to run to completion?

**Comment by apeltzer** [comment]
Yes it did!!!

```
sh runDeepvariant.sh
N E X T F L O W  ~  version 18.10.1
Launching `nf-core/deepvariant` [evil_pesquet] - revision: f24c49cabb [dev]
=======================================================
                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~'
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'
nf-core/deepvariant v1.0dev"
=======================================================
Pipeline Name  : nf-core/deepvariant
Pipeline Version: 1.0dev
Bam file       : hroc113_0.md.bam
Bed file       : /beegfs/work/iiipe01/2018-10-21_DeepVariant_Test/WES_targets_centogene.bed
Fasta Ref      : /beegfs/work/iiipe01/Reference_Genomes/Human/GRCH37-Sarek/human_g1k_v37_decoy.fasta
Max Memory     : 128 GB
Max CPUs       : 28
Max Time       : 2d
Model          : wes
Output dir     : results
Working dir    : /beegfs/work/iiipe01/2018-10-21_DeepVariant_Test/work
Container Engine: singularity
Container      : nfcore/deepvariant:latest
Current home   : /home-link/iiipe01
Current user   : iiipe01
Current path   : /beegfs/work/iiipe01/2018-10-21_DeepVariant_Test
Script dir     : /home-link/iiipe01/.nextflow/assets/nf-core/deepvariant
Config Profile : binac
=========================================
[warm up] executor > pbs
[9c/581fc2] Cached process > preprocess_fai (human_g1k_v37_decoy.fasta.fai)
[43/dceebb] Cached process > preprocess_bam (hroc113_0.md.bam)
[6b/3c32b0] Cached process > preprocess_gzi (human_g1k_v37_decoy.fasta.gz.gzi)
[3c/f89af0] Cached process > preprocess_fastagz (human_g1k_v37_decoy.fasta.gz)
[75/e53133] Submitted process > get_software_versions
[ac/f03f86] Cached process > preprocess_gzfai (human_g1k_v37_decoy.fasta.gz.fai)
[74/d5b07b] Submitted process > make_examples (hroc113_0.md.bam)
[a9/e2f586] Submitted process > call_variants (hroc113_0.md.bam)
[2f/599902] Submitted process > postprocess_variants (hroc113_0.md.bam)
a[nf-core/deepvariant] Pipeline Complete! You can find your results in /home-link/iiipe01/.nextflow/assets/nf-core/deepvariant/results
[iiipe01@login03 2018-10-21_DeepVariant_Test]$ a
```

**Comment by apeltzer** [comment]
Which in turns means, I'm happy if you do a release now :-)

**Comment by leorippel** [comment]
Sorry to comment in a closed thread. I'm having the same issue. How is solved, is a memory thing?

```console
$ nextflow run nf-core/deepvariant    --fasta /home/rippell/data/GATK/10consensus.fasta --fai /home/rippell/data/GATK/10consensus.fasta.fai --bam /home/rippell/data/GATK/i7-97_sorted_reads.bam --bed /home/rippell/data/GATK/i7-97_sorted_reads.bed --max_memory 24.GB --max_cpus 3 -profile standard,docker -resume

N E X T F L O W  ~  version 20.04.1
Launching `nf-core/deepvariant` [infallible_engelbart] - revision: 2b5486356c [master]

executor >  local (1)
[99/9cff25] process > preprocess_fastagz (10consensus.fasta.gz)   [100%] 1 of 1, cached: 1 ✔
[d9/8d8851] process > preprocess_gzfai (10consensus.fasta.gz.fai) [100%] 1 of 1, cached: 1 ✔
[32/8ea296] process > preprocess_gzi (10consensus.fasta.gz.gzi)   [100%] 1 of 1, cached: 1 ✔
[49/356721] process > preprocess_bam (i7-97_sorted_reads.bam)     [100%] 1 of 1, cached: 1 ✔
[f7/d63e97] process > make_examples (i7-97_sorted_reads.bam)      [100%] 1 of 1, failed: 1 ✘
[-        ] process > call_variants                               -
[-        ] process > postprocess_variants                        -
[2a/f81c8e] process > get_software_versions                       [100%] 1 of 1, cached: 1 ✔
Execution cancelled -- Finishing pending tasks before exit


Error executing process > 'make_examples (i7-97_sorted_reads.bam)'

Caused by:
  Process `make_examples (i7-97_sorted_reads.bam)` terminated with an error exit status (247)

Command executed:

  mkdir logs
  mkdir i7-97_sorted_reads_shardedExamples
  dv_make_examples.py   --cores 3   --sample i7-97_sorted_reads.bam   --ref 10consensus.fasta.gz   --reads i7-97_sorted_reads.bam   --regions i7-97_sorted_reads.bed   --logdir logs   --examples i7-97_sorted_reads_shardedExamples

Command exit status:
  247

Command output:
  (empty)

ETA: 0s Left: 3 AVG: 0.00s  local:3/0/100%/0.0s 2020-07-14 02:04:41.102417: W third_party/nucleus/io/sam_reader.cc:537] Unrecognized SAM header type, ignoring: 
  I0714 02:04:41.361650 139962022872832 genomics_reader.py:213] Reading i7-97_sorted_reads.bam with NativeSamReader
  I0714 02:04:41.711935 139962022872832 make_examples.py:1075] Preparing inputs
  2020-07-14 02:04:43.268289: W third_party/nucleus/io/sam_reader.cc:537] Unrecognized SAM header type, ignoring: 
  I0714 02:04:43.512497 139962022872832 genomics_reader.py:213] Reading i7-97_sorted_reads.bam with NativeSamReader
  I0714 02:06:47.752322 139962022872832 make_examples.py:991] Common contigs are [u'disjointig_1', u'disjointig_10', u'disjointig_100', u'disjointig_1000', u'disjointig_10000', u'disjointig_100000', u'disjointig_100001', u'disjointig_100002', u'disjointig_100003', u'disjointig_100004', u'disjointig_100005', u'disjointig_100006', u'disjointig_100007', u'disjointig_100008', u'disjointig_100009', u'disjointig_10001', u'disjointig_100010', u'disjointig_100011', u'disjointig_100012', u'disjointig_100013', u'disjointig_100014', u'disjointig_100015', u'disjointig_100016', u'disjointig_100017', u'disjointig_100018', u'disjointig_100019', u'disjointig_10002', u'disjointig_100020', u'disjointig_100021', u'disjointig_100022', u'disjointig_100023', u'disjointig_100024', u'disjointig_100025', u'disjointig_100026', u'disjointig_100027', u'disjointig_100028', u'disjointig_100029', u'disjointig_10003', u'disjointig_100030', u'disjointig_100031', u'disjointig_100032', u'disjointig_1000

Command error:
  ETA: 0s Left: 3 AVG: 0.00s  local:3/0/100%/0.0s 


parallel: This job failed:
  /opt/conda/envs/nf-core-deepvariant-1.0/bin/python /opt/conda/envs/nf-core-deepvariant-1.0/share/deepvariant-0.7.0-0/binaries/DeepVariant/0.7.0/DeepVariant-0.7.0+cl-208818123/make_examples.zip --mode calling --ref 10consensus.fasta.gz --reads i7-97_sorted_reads.bam --regions i7-97_sorted_reads.bed --examples i7-97_sorted_reads_shardedExamples/i7-97_sorted_reads.bam.tfrecord@3.gz --task 2

Work dir:
  /home/rippell/data/GATK/work/95/514c9ed1d1491443b784e05a064982

```
