### ISSUE TITLE
Set up Template branch

### ISSUE THREAD

**Issue by apeltzer** [nf-core/deepvariant#9]
See here for details: https://nf-co.re/sync

**Comment by PhilPalmer** [comment]
@apeltzer I've added the template branch, followed the synchronization instructions and just released DeepVariant 🎉  

Thanks for your help. I'm sure it was a bit more involved with the testing than you intially had in mind 😅

**Comment by apeltzer** [comment]
I intend to use the pipeline so happy to help out here ;-)
